# Generated by Django 4.1.1 on 2023-09-26 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_mimicnumber_txreplacementrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoadSheddingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='HVReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outage_description', models.CharField(max_length=1000)),
                ('date_out', models.DateField(null=True)),
                ('time_out', models.TimeField(null=True)),
                ('date_restored', models.DateField(null=True)),
                ('time_restored', models.TimeField(null=True)),
                ('duration', models.CharField(max_length=100)),
                ('cause', models.CharField(max_length=1000)),
                ('remarks', models.CharField(max_length=1000)),
                ('feeder', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hv_report_feeder', to='base.feeder')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hv_report', to='reports.basereport')),
            ],
        ),
    ]
