# Generated by Django 4.1.1 on 2023-09-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_basereport_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basereport',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='hvreport',
            name='load',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
