# Generated by Django 4.1.1 on 2023-10-23 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_forcedoutagereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='forcedoutagereport',
            name='hold_date_time_retored',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='forcedoutagereport',
            name='affected_areas',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='forcedoutagereport',
            name='cause',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='forcedoutagereport',
            name='hold_date_time_out',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='forcedoutagereport',
            name='outage_description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='forcedoutagereport',
            name='remarks',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='forcedoutagereport',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forced_outage_records', to='reports.basereport'),
        ),
    ]
