# Generated by Django 4.1.1 on 2023-10-11 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_mimicnumber_txreplacementrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='mimicnumber',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='mimicnumber',
            name='description',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='mimicnumber',
            name='feeder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.feeder'),
        ),
        migrations.AddField(
            model_name='mimicnumber',
            name='location',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='mimicnumber',
            name='mimic_number',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mimicnumber',
            name='size',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='txreplacementrecord',
            name='capacity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='txreplacementrecord',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='txreplacementrecord',
            name='feeder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.feeder'),
        ),
        migrations.AddField(
            model_name='txreplacementrecord',
            name='location',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='txreplacementrecord',
            name='manufacturer',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='txreplacementrecord',
            name='remarks',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='txreplacementrecord',
            name='serial_number',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='txreplacementrecord',
            name='substation_number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='txreplacementrecord',
            name='year',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
