# Generated by Django 4.1.1 on 2023-10-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_mimicnumber_date_mimicnumber_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mimicnumber',
            name='mimic_number',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
